version: '3.1'

networks:
  link_creator:

services:
  link-creator-app:
    container_name: link-creator-app
    build:
      context: .docker/app
      dockerfile: Dockerfile-dev
    volumes:
      - ".:/var/www/link_creator"
    extra_hosts:
      - "host.docker.internal:host-gateway" # For xdebug
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal
      PHP_IDE_CONFIG: serverName=link-creator-app
    env_file:
      - .env.local
    networks:
      - link_creator
    hostname: link-creator.res

  link-creator-db:
    container_name: link-creator-db
    image: postgres:alpine
    volumes:
      - /home/user/projects/my-projects/storeges/link_creator/postgres/:/var/lib/postgresql/data/
    ports:
      - 6440:5432
    hostname: link-creator.res
    env_file:
      - .env.local
    environment:
      POSTGRES_PASSWORD: ${SQL_DB_PASSWORD:-developer}
      POSTGRES_USER: ${SQL_DB_USER:-developer}
      POSTGRES_DB: ${SQL_DB_NAME:-postgesql}
    command: [ "postgres", "-c", "log_statement=all" ]
    networks:
      - link_creator

  link-creator-nginx:
    container_name: link-creator-nginx
    image: nginx:alpine
    ports:
      - ${NGINX_PORT:-8122}:8122
    volumes:
      - ".:/var/www/link_creator"
      - ".docker/nginx/conf.d/link-creator.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - link-creator-app
    networks:
      - link_creator
    hostname: link-creator.res

#  mailer:
#    container_name: link-creator-mailer
#    image: axllent/mailpit
#    ports:
#      - "1025:1025"
#      - "8025:8025"
#    environment:
#      MAILPIT_WEB_HOST: 0.0.0.0
#      MP_SMTP_AUTH_ACCEPT_ANY: 1
#      MP_SMTP_AUTH_ALLOW_INSECURE: 1
